volumes:
  db_data:
    driver: local

services:
  db:
    container_name: smart-scheduling-db
    build: environment_development/postgresql/.
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smart_scheduling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
