volumes:
  db_data:
    driver: local
  maven-cache: 

services:
  db:
    container_name: smart-scheduling-db
    build: environment_development/postgresql/.
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smart_scheduling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

  backend:
    container_name: smart-scheduling-back
    build:
      context: ./back-end
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
    container_name: smart-scheduling-front
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    container_name: smart-scheduling-nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend